# This workflow will triage pull requests and apply a label based on the path. 
# To use this workflow, you will need to set up a .github/labeler.yml file with configuration.

name: Labeler
on: [pull_request]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - uses: actions/labeler@v2
      with:
        repo-token: "${{ secrets.TOKEN }}"
