name: Release

on:
  push:
    tags:
      - "v*.*.*"

env:
  NODEVERSION: 16.x

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: set env variable
        run: echo "RELEASE_VERSION=${GITHUB_REF:11}" >> $GITHUB_ENV
      - name: set environment variable
        run: echo ${{ env.RELEASE_VERSION }}
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v1
        with:
          images: tolatemitope/chainsafedevops
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}