name: unit-test

on:
  pull_request:
    branches:
      - master

jobs:
  test-unit:
    name: Run test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node:
          - 12.x
          - 13.x
          - 14.x
          - 15.x
          - 16.x
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
      - run: npm install
      - run: npm run test
